export const activites = [
  "Coaching",
  "Marketing et communication",
  "Commerce",
  "E-commerce",
  "Action sociale/Association",
  "Tourisme, Voyage, hôtellerie",
  "Chimie, biologie, biotechnologie",
  "Numérique, Technologie, Deeptech",
  "Artisanat",
  "Sport, animation et loisir",
  "Défense et sécurité",
  "Services à la personne",
  "Bien-être",
  "Médecine alternative",
  "Restauration",
  "Industrie",
  "Agriculture, agroalimentaire",
  "Audiovisuel, journalisme",
  "Beauté et esthétique",
  "Enseignement et formation",
  "Services aux entreprises",
  "Etudes et conseils",
  "Edition, imprimerie, livre",
  "Activités juridiques et comptables",
  "Finance, banque et assurance",
  "Gestion administrative et ressources humaines",
  "Immobilier",
  "Textile et mode",
  "Informatique et télécommunication",
  "BTP, urbanisme",
  "Service public, défense et sécurité",
  "Culture et patrimoine",
  "Recherche scientifique",
  "Architecture, décoration",
  "Electronique, robotique",
  "Environnement",
  "Santé, paramédical",
  "Transport, logistique",
  "Mécanique, automobile, métallurgie",
  "Autre",
];

export const regions = [
  "Auvergne-Rhône-Alpes",
  "Bourgogne-Franche-Comté",
  "Bretagne",
  "Centre-Val de Loire",
  "Corse",
  "Grand Est",
  "Hauts-de-France",
  "Île-de-France",
  "Normandie",
  "Nouvelle-Aquitaine",
  "Occitanie",
  "Pays de la Loire",
  "Provence-Alpes-Côte d’Azur",
  "Guadeloupe",
  "Martinique",
  "Guyane",
  "La Réunion",
  "Mayotte",
];
